### ISSUE TITLE
automated tests?

### ISSUE THREAD

**Issue by gregcaporaso** [joonro/Org-Coursepack#1]
I'm currently [reviewing the Org-Coursepack paper for Jose](https://github.com/openjournals/jose-reviews/issues/34). 

I don't see automated tests for Org-Coursepack. Are those possible to add? It would be nice to at least see automated integration tests, where on each change, TravisCI (or some other service) runs to convert example source content into all of the different products (slides, handouts, ...).

**Comment by joonro** [comment]
Hi - 

I'm sorry for the delay. I looked into incorporating TravisCI, but given that `org-coursepack` is a template mainly consists of files written in org-markup, it was not clear which part I should make tests for, except for the `Update Lectures` script which automatically updates class number, class agenda, etc for each class.

Could you please advise us the kind of tests that we can provide? Please let me know and thank you very much.

**Comment by gregcaporaso** [comment]
I would recommend some sort of tests that confirm that the products can be created from the source content, but since I'm not an Org user, I'm not sure that this is possible or something that makes sense to add.

**Comment by gregcaporaso** [comment]
Tests look great @joonro!
