### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by gregcaporaso** [joonro/Org-Coursepack#2]
I'm currently [reviewing the Org-Coursepack paper for Jose](https://github.com/openjournals/jose-reviews/issues/34). 

There are no contributing guidelines that I see. At the least, it would be nice for the authors to include a CONTRIBUTING.md file.

**Comment by joonro** [comment]
Dear @gregcaporaso, we just added [CONTRIBUTING.md](https://github.com/joonro/Org-Coursepack/blob/feature/CONTRIBUTING.md/CONTRIBUTING.md) (commit: 51c28d283995fdac8ce6f54d9284c03751b6f5ad). Please let me know if you need anything else regarding this issue. We will work on making the quickstarter guide. Thank you very much!

**Comment by gregcaporaso** [comment]
Looks great!
