### ISSUE TITLE
quickstart guides?

### ISSUE THREAD

**Issue by gregcaporaso** [joonro/Org-Coursepack#3]
I'm currently [reviewing the Org-Coursepack paper for Jose](https://github.com/openjournals/jose-reviews/issues/34). 

As a non-Org-user, I find the documentation a little overwhelming. I'd like to see some sort of a quickstart guide if that's possible to develop - for example, this could cover opening one of the example courses, and then running a few commands to export slides, lecture outlines, and exams. Then, dive into the details that are covered in the [primary documentation](https://joonro.github.io/Org-Coursepack/). This would make sense to include in the _Introduction_ section, in my opinion. As it stands, I think the emacs/Org knowledge/skills required to use Org-Coursepack will be a barrier to obtaining new users. 

Quickstart installation instructions could also be helpful - for example, could full installation be achieved with Anaconda, or another package manager (e.g., for the users who don't have emacs, reveal, or latex installed)? I was able to install the necessary components, but it did involve navigating to three different project websites (emacs, org-reveal, latex) to install different dependencies. This isn't essential, but it would likely help attract new users.

**Comment by joonro** [comment]
Dear @gregcaporaso,

As I replied in the [review page](https://github.com/openjournals/jose-reviews/issues/34#issuecomment-449792558), we added quickstart guide as well as more comprehensive installation instructions to the repo. Importantly, we also added an [example init file](https://github.com/joonro/Org-Coursepack/blob/master/Assets/.emacs.d/init.el), which will automatically take care of installation of necessary Emacs packages along with containing necessary settings. 

We believe now users can easily install and start using Org-Coursepack. Please let me know if you need anything else regarding this issue, and thank you again for your feedback.

**Comment by gregcaporaso** [comment]
Looks great!
